const $=s=>document.querySelector(s),form=$('#editor');let works=[];
const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
async function api(path,method='GET',data){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const result=await r.json();if(!r.ok){if(r.status===401){$('#dashboard').hidden=true;$('#login').hidden=false;$('#logout').hidden=true;}throw Error(result.error||'Request failed. Please try again.');}return result;}
function status(message,error=false){$('#studio-status').textContent=message;$('#studio-status').className=error?'error':'';}
function clear(){form.reset();form.elements.id.value='';form.elements.image.value='';form.elements.year.value=new Date().getFullYear();form.elements.position.value=0;$('#preview').hidden=true;$('#editor-heading').textContent='Add an artwork';$('#editor-status').textContent='';}
async function list(){works=await api('works?admin=1');$('#work-list').replaceChildren();for(const w of works){const row=node('div','');row.className='studio-row';const text=node('div',w.title);text.append(node('small',`${w.year} · ${w.published?'Published':'Draft'} · Order ${w.position}`));const edit=node('button','Edit');edit.onclick=()=>{clear();for(const key of ['id','image','title','year','medium','dimensions','alt','notes','position'])form.elements[key].value=w[key]||'';form.elements.position.value=w.position;form.elements.published.checked=w.published;$('#preview').src=w.image;$('#preview').hidden=false;$('#editor-heading').textContent='Edit artwork';form.scrollIntoView({behavior:'smooth'});};const del=node('button','Delete');del.onclick=async()=>{if(!confirm(`Remove “${w.title}” from the site? This cannot be undone.`))return;del.disabled=true;try{await api('works','DELETE',{id:w.id});await list();if(form.elements.id.value===w.id)clear();}catch(e){status(e.message,true);}finally{del.disabled=false;}};row.append(text,edit,del);$('#work-list').append(row);}if(!works.length)$('#work-list').textContent='No artworks yet. Add your first work using the form.';}
async function inbox(){try{const messages=await api('inbox');$('#inbox').replaceChildren();for(const m of messages){const item=node('article','');item.className='inbox-item';item.append(node('h3',m.subject),node('small',`${m.name} · ${m.email} · ${new Date(m.created_at).toLocaleString()}`),node('p',m.message));const reply=node('a','Reply by email ↗');reply.href=`mailto:${encodeURIComponent(m.email)}?subject=${encodeURIComponent('Re: '+m.subject)}`;reply.className='text-link';const remove=node('button','Delete enquiry');remove.onclick=async()=>{if(!confirm('Permanently delete this enquiry?'))return;try{await api('inbox','DELETE',{id:m.id});await inbox();}catch(e){status(e.message,true);}};item.append(reply,remove);$('#inbox').append(item);}if(!messages.length)$('#inbox').textContent='No enquiries yet. New messages from your website will appear here.';}catch(e){$('#inbox').textContent=e.message;}}
async function enter(){$('#login').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;status('');await list();await inbox();}
$('#login').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('session','POST',{password:e.target.elements.password.value});e.target.reset();await enter();}catch(err){status(err.message,true);}finally{button.disabled=false;}};
$('#logout').onclick=async()=>{try{await api('session','DELETE');location.reload();}catch(e){status(e.message,true);}};
$('#upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;const s=$('#editor-status');if(file.size>3000000){s.textContent='Choose an image smaller than 3 MB.';e.target.value='';return;}$('#save').disabled=true;s.textContent='Uploading image…';try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Could not read image.'));reader.readAsDataURL(file);});const result=await api('upload','POST',{data});form.elements.image.value=result.image;$('#preview').src=result.image;$('#preview').hidden=false;s.textContent='Image uploaded. Save the artwork to publish your changes.';}catch(err){s.textContent=err.message;e.target.value='';}finally{$('#save').disabled=false;}};
form.onsubmit=async e=>{e.preventDefault();const s=$('#editor-status'),data=Object.fromEntries(new FormData(form));data.published=form.elements.published.checked;if(!data.image){s.textContent='Please upload an artwork image.';return;}$('#save').disabled=true;s.textContent='Saving…';try{await api('works',data.id?'PUT':'POST',data);clear();s.textContent='Artwork saved.';await list();}catch(err){s.textContent=err.message;}finally{$('#save').disabled=false;}};
$('#new-work').onclick=()=>{clear();form.scrollIntoView({behavior:'smooth'});};$('#cancel-edit').onclick=clear;$('#refresh-inbox').onclick=inbox;
clear();api('session').then(async s=>{if(s.authenticated)await enter();else if(!s.configured)status('Studio setup is pending. Connect the database and add the environment variables listed in README.md.',true);}).catch(e=>status(e.message,true));
