import { createHmac, timingSafeEqual, createHash } from 'node:crypto';
export const configured=()=>Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);
export function fail(message,status=400){const e=new Error(message);e.status=status;throw e;}
export function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data));}
export async function body(req){if(req.body){if(typeof req.body==='string')return JSON.parse(req.body);return req.body;}let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>4_100_000)fail('File is too large.',413);}try{return JSON.parse(raw||'{}');}catch{fail('Invalid request.');}}
export function method(req,allowed){if(!allowed.includes(req.method))fail('Method not allowed.',405);if(req.method!=='GET'){const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)fail('Request origin is not allowed.',403);}}
export function wrap(fn){return async(req,res)=>{try{await fn(req,res);}catch(e){if(!e.status)console.error('API failure:',e.message);json(res,e.status||503,{error:e.status?e.message:'This service is temporarily unavailable. Please try again or email aggelos.giannoul@gmail.com.'});}};}
export async function db(path,options={}){if(!configured())fail('The studio is not connected yet. Please email aggelos.giannoul@gmail.com.',503);const r=await fetch(process.env.SUPABASE_URL+path,{...options,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Storage request failed: '+r.status);const t=await r.text();return t?JSON.parse(t):null;}
const secret=()=>process.env.SESSION_SECRET||'';
const sign=s=>createHmac('sha256',secret()).update(s).digest('hex');
export const equal=(a,b)=>timingSafeEqual(createHash('sha256').update(String(a)).digest(),createHash('sha256').update(String(b)).digest());
export function isAdmin(req){if(secret().length<32)return false;const cookie=(req.headers.cookie||'').split('; ').find(c=>c.startsWith('studio_session='))?.slice(15);if(!cookie)return false;const [expiry,sig]=cookie.split('.');return Number(expiry)>Date.now()&&equal(sig,sign(expiry));}
export function requireAdmin(req){if(!isAdmin(req))fail('Please sign in to your studio.',401);}
export function sessionCookie(req,logout=false){const expiry=String(Date.now()+8*60*60*1000);return `studio_session=${logout?'':expiry+'.'+sign(expiry)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${logout?0:28800}${process.env.VERCEL||process.env.NODE_ENV==='production'?'; Secure':''}`;}
export function text(value,max,required=true){if(typeof value!=='string'||value.trim().length>max||(required&&!value.trim()))fail('Please check the required fields and their lengths.');return value.trim();}
export async function rate(req,scope,limit){const ip=req.headers['x-vercel-forwarded-for']||req.socket?.remoteAddress||'unknown';const key=createHash('sha256').update(scope+ip+secret()).digest('hex');const ok=await db('/rest/v1/rpc/check_rate',{method:'POST',body:JSON.stringify({key_value:key,max_hits:limit})});if(!ok)fail('Too many attempts. Please try again in 15 minutes.',429);}
export function validateWork(b){const year=Number(b.year),position=Number(b.position);if(!Number.isInteger(year)||year<1900||year>new Date().getFullYear()+1)fail('Please enter a valid artwork year.');if(!Number.isInteger(position)||position<0||position>9999)fail('Please enter an order between 0 and 9999.');if(typeof b.published!=='boolean')fail('Choose draft or published.');const image=text(b.image,1000);const base=process.env.SUPABASE_URL+'/storage/v1/object/public/artworks/';if(!/^\/assets\/art\/p\d+\.jpg$/.test(image)&&!image.startsWith(base))fail('Please upload an artwork image first.');return {title:text(b.title,250),year,medium:text(b.medium,200),dimensions:text(b.dimensions||'',100,false),notes:text(b.notes||'',3000,false),alt:text(b.alt,500),image,position,published:b.published};}
